spring:
  application:
    name: sender

server:
  port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

services:
  receiver:
    name: receiver
    port: 8091